### ISSUE TITLE
Improve OpenSSF Scorecard

### ISSUE THREAD

**Issue by jab** [jab/bidict#253]
Ref:
- https://deps.dev/pypi/bidict
- https://github.com/ossf/scorecard/blob/main/docs/checks.md

<img width="439" alt="Screen Shot 2022-08-06 at 2 54 43 PM" src="https://user-images.githubusercontent.com/64992/183262408-6ab1a37c-7089-4778-8b07-c5b2d81da188.png">

**Comment by jleclanche** [comment]
IMO dependency pinning is the only "real" item in this list.

I think it would be helped by switching to [Poetry](https://python-poetry.org/) for dependency management. Do you want some help with this?

**Comment by jab** [comment]
Already pinning dependencies to exact versions, just not yet using hashes. There should be no need to switch to poetry for that though, as pip and pip-compile-multi support that already. Just tried in 3c385d5b6829a6724e457d21809d8c830c784485 but hit Python version-specific inconsistencies that cause installation to fail for some Python versions when the requirements were generated via pip-compile-multi running from a different Python version (see e.g. https://github.com/jab/bidict/actions/runs/3560472842/jobs/5980516165#step:7:131). Have to put this aside for now. Should have time to pick it back up next weekend. Feel free to take a look in the meantime if you're interested, and thanks for offering!

**Comment by jleclanche** [comment]
Yeah, I've had a horrendous experience with pip-compile-multi, and this is a good example why…
IMO Poetry just does things "right". Dependency management in pyproject.toml, follows pep 518/621, lockfile is separate.

**Comment by jleclanche** [comment]
@jab If you want, here's a pyproject.toml file with poetry set up. The only thing I couldn't quickly check is how your includes and excludes would look; poetry does a lot of things out of the box so you don't need to mess about with manifest files.


```toml
[tool.poetry]
name = "bidict"
version = "0.22.1.dev0"
description = "The bidirectional mapping library for Python."
license = "MPL 2.0"
authors = [
    "Joshua Bronson <jabronson@gmail.com>",
]
readme = "README.rst"
homepage = "https://bidict.readthedocs.io"
repository = "https://github.com/jab/bidict"
documentation = "https://bidict.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
keywords = [
    "dict", "dictionary", "mapping", "datastructure", "bimap", "bijection",
    "bijective", "injective", "inverse", "reverse", "bidirectional", "two-way",
    "2-way"
]
packages = [
    { include = "bidict" }
]
include = [
    "LICENSE", # ...
]
exclude = [
    # ...
]

[tool.poetry.urls]
"Donate" = "https://github.com/sponsors/jab"
"Enterprise Support" = "https://bidict.readthedocs.io/#enterprise-support"
"Changelog" = "https://bidict.readthedocs.io/changelog.html"
"Issue Tracker" = "https://github.com/jab/bidict/issues"
"Chat" = "https://gitter.im/jab/bidict"

[tool.poetry.dependencies]
python = "^3.7.2"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
check-manifest = "^0.48"
pre-commit = "^2.20.0"
tox = "^3.27.1"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
furo = "^2022.9.29"
sphinx = "^5.3.0"
sphinx-copybutton = "^0.5.1"

[tool.poetry.group.lint.dependencies]
pre-commit = "^2.20.0"
pylint = "^2.15.6"
pytest = "^7.2.0"
hypothesis = "^6.58.1"

[build-system]
requires = ["poetry_core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
```
